# Generated by Django 4.2.3 on 2023-12-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='death_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='death_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='death_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='enslavement_status',
            field=models.IntegerField(choices=[(1, 'enslaved'), (2, 'enslaved, then free'), (3, 'always free'), (4, 'enslaver'), (5, 'not enslaver')], default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('select', 'please select'), ('male', 'male'), ('female', 'female'), ('unknown', 'unknown')], default='select', max_length=12),
        ),
        migrations.AddField(
            model_name='person',
            name='menu_blurb',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='person',
            name='prod_status',
            field=models.IntegerField(choices=[(0, 'entered'), (1, 'draft'), (3, 'show')], default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
    ]
