# Generated by Django 4.2.3 on 2023-12-04 21:32

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_birth_day_person_birth_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=django_quill.fields.QuillField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='person',
            name='enslavement_status',
            field=models.IntegerField(choices=[(0, 'please select'), (1, 'enslaved'), (2, 'enslaved, then free'), (3, 'always free'), (4, 'enslaver'), (5, 'not enslaver')], default=0),
        ),
    ]
