# Generated by Django 4.2.3 on 2023-12-04 22:03

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_person_bio_person_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fake_related',
            field=django_quill.fields.QuillField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(max_length=32, unique=True),
        ),
    ]
