# Generated by Django 4.2.3 on 2023-12-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='prod_status',
            field=models.IntegerField(choices=[(0, 'hide'), (1, 'show'), (2, 'active')], default=1),
        ),
    ]
