# Generated by Django 4.2.3 on 2023-12-15 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_person_notes_alter_person_prod_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='prod_status',
            field=models.IntegerField(choices=[(0, 'background'), (1, 'proto-menu'), (2, 'proto-detail')], default=1),
        ),
        migrations.AlterField(
            model_name='related',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relateds', to='people.person'),
        ),
    ]
