# Generated by Django 4.2.3 on 2024-02-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_alter_person_prod_status_alter_related_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='prod_status',
            field=models.IntegerField(choices=[(0, 'background'), (1, 'proto-menu'), (2, 'proto-detail')], default=0),
        ),
    ]
