# Generated by Django 4.2.3 on 2024-04-09 21:18

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_alter_person_prod_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='has_more',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='more_text',
            field=django_quill.fields.QuillField(blank=True, default=''),
        ),
    ]
