# Generated by Django 4.2.3 on 2024-06-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_related_content_type_related_slug_alter_related_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_text',
            field=models.CharField(blank=True, default='', help_text='Only if exact year unknown', max_length=24),
        ),
        migrations.AddField(
            model_name='person',
            name='death_text',
            field=models.CharField(blank=True, default='', help_text='Only if exact year unknown', max_length=24),
        ),
    ]
