# Generated by Django 4.2.3 on 2024-06-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_related_content_type_related_slug_alter_related_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='map',
            name='ordinal',
            field=models.IntegerField(default=99),
        ),
    ]
