# Generated by Django 4.2.3 on 2023-12-05 19:33

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('menu_blurb', models.TextField(blank=True, default='')),
                ('full_text', django_quill.fields.QuillField(blank=True, default='')),
                ('item_type', models.CharField(choices=[('object', 'Object'), ('document', 'Document')], default='select', max_length=12)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=128)),
                ('citation', models.CharField(blank=True, default='', max_length=128)),
                ('accession_num', models.CharField(blank=True, default='', max_length=32)),
            ],
        ),
    ]
