# Generated by Django 4.2.3 on 2023-12-15 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_evidenceitem_notes_evidenceitem_prod_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceitem',
            name='item_type',
            field=models.CharField(choices=[('manuscript', 'Manuscripts'), ('printed', 'Printed material'), ('object', 'Objects'), ('picture', 'Pictures and Paintings')], default='select', max_length=12),
        ),
        migrations.AlterField(
            model_name='evidenceitem',
            name='prod_status',
            field=models.IntegerField(choices=[(0, 'background'), (1, 'proto-menu'), (2, 'proto-detail')], default=1),
        ),
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=32)),
                ('evidence_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relateds', to='evidence.evidenceitem')),
            ],
        ),
    ]
