# Generated by Django 4.2.3 on 2024-02-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_alter_evidenceitem_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenceitem',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='isCirca',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evidenceitem',
            name='prod_status',
            field=models.IntegerField(choices=[(0, 'background'), (1, 'proto-menu'), (2, 'proto-detail')], default=0),
        ),
    ]
