# Generated by Django 4.2.3 on 2024-02-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0004_evidenceitem_caption_evidenceitem_end_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidenceitem',
            old_name='isCirca',
            new_name='is_circa',
        ),
        migrations.AlterField(
            model_name='evidenceitem',
            name='end_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='End, if range'),
        ),
    ]
