# Generated by Django 4.2.3 on 2024-05-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0006_related_content_type_related_slug_alter_related_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenceitem',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
    ]
