# Generated by Django 4.2.3 on 2023-12-15 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topic_notes_topic_prod_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='theme',
            field=models.IntegerField(choices=[(0, 'Myths'), (1, 'Emancipation'), (2, 'Another Theme')], default=1),
        ),
        migrations.AlterField(
            model_name='topic',
            name='prod_status',
            field=models.IntegerField(choices=[(0, 'background'), (1, 'proto-menu'), (2, 'proto-detail')], default=1),
        ),
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=32)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relateds', to='topics.topic')),
            ],
        ),
    ]
