# Generated by Django 4.2.3 on 2024-02-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_topic_theme_alter_topic_prod_status_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='prod_status',
            field=models.IntegerField(choices=[(0, 'background'), (1, 'proto-menu'), (2, 'proto-detail')], default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='theme',
            field=models.IntegerField(choices=[(0, 'Select a Theme'), (1, 'EncodingWarningStruggle for Freedom'), (2, 'A Slave Economy'), (3, 'The Variety of Enlaved Experience (draft)'), (4, 'Control and Resistance'), (5, 'Revolutionary Ideals and Liberty'), (6, 'Holding On to Humanity'), (7, 'Myths and Assumptions')], default=0),
        ),
    ]
