# Generated by Django 4.2.3 on 2024-04-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_topic_has_video_alter_topic_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='topic',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
    ]
