"""
Django settings
Generated by 'django-admin startproject' using Django 4.2.3.
"""
import json
from pathlib import Path
# Normally you should not import ANYTHING from Django directly 
# into your settings, but ImproperlyConfigured is an exception. 
# For secret key retrieval
from django.core.exceptions import ImproperlyConfigured
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# JSON-based secrets module
with open(BASE_DIR / 'config' / 'settings' / 'secrets.json') as f:
    secrets = json.loads(f.read())

def get_secret(which_key, secrets=secrets):
    """ Get the secret variable or return explicit exception. """
    try:
        return secrets[which_key]
    except KeyError:
        error_msg = "Set the {0} environment variable".format(which_key)
        raise ImproperlyConfigured(error_msg)

SECRET_KEY = get_secret("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['lucy-proto.deerfield-ma.org', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'apps.moments.apps.MomentsConfig',
    'apps.evidence.apps.EvidenceConfig',
    'apps.people.apps.PeopleConfig',
    'apps.topics.apps.TopicsConfig',
    'apps.myths.apps.MythsConfig',
    'apps.maps.apps.MapsConfig',
    'apps.sitewide.apps.SitewideConfig',
    'rest_framework',
    'django_quill',
    'django_htmx',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_WHITELIST = [
    "https://lucy-app-b8qj5.ondigitalocean.app/",
    "http://127.0.0.1:8000/",
    "https://lucy-proto.deerfield-ma.org",
    "http://localhost:5173"
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'lucy_db',
        'USER': 'lucy_db_user',
        'PASSWORD': get_secret("DB_PASS"),
        'HOST': '127.0.0.1',
        'PORT': '5432',        
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_DIRS = [BASE_DIR / 'apps' / 'local_static']

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR.parents[0] / "lucy-static"

# MEDIA_URL = 'media/'
# MEDIA_ROOT = BASE_DIR.parents[0] / "lucy-media"

# Custom setting
ASSET_PATH = "/assets"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
